# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scheduler.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scheduler(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 192)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 30, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(165, 120, 61, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("QPushButton{\n"
                                     "    font-family: Arial;border: 1px solid  #292929;color: #292929; \n"
                                     "    font-weight: bold; font-size: 16px\n"
                                     "}\n"
                                     "QPushButton:hover{                    \n"
                                     "    border: 0px solid7;\n"
                                     "    color:white;background: #292929;\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "    background:#353535;\n"
                                     "}")
        self.pushButton.clicked.connect(lambda: self.close_window(Dialog))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Daily routine measurment"))
        self.label.setText(_translate("Dialog", "Please measure your weight \n"
"and Blood Pressure."))
        self.pushButton.setText(_translate("Dialog", "ok"))

    def close_window(self, Dialog):
        Dialog.close()


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_scheduler()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())