# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bm_connection_tips.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from qasync import QtGui

from view.measurement.bm_measurement.bm_measure import Ui_Dialog
"""
Author: GRP group 14
"""
class Ui_test(object):
    def setup(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 230, 350, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setStyleSheet("QPushButton{\n"
                                             "    font-family: Arial;border: 1px solid  #292929;color: #292929; \n"
                                             "    font-size: 14px; font-weight: bold; padding:5px;\n"
                                             "}\n"
                                             "QPushButton:hover{                    \n"
                                             "    border: 0px solid7;\n"
                                             "    color:white;background: #292929;\n"
                                             "}\n"
                                             "QPushButton:pressed{\n"
                                             "    background:#353535;\n"
                                             "}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(25, 80, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:22px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(25, 120, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size:22px")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(lambda: self.close_window(Dialog))
        self.buttonBox.accepted.connect(self.open_bt_measure)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def open_bt_measure(self):
        self.window = QtWidgets.QDialog()
        self.weight_measure = Ui_Dialog()
        self.weight_measure.setup(self.window)
        self.window.show()

    def close_window(self,current_window):
        current_window.close()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "STEP1: Get on the scale"))
        self.label_2.setText(_translate("Dialog", "STEP2: Press the start button"))

if __name__ == "__main__":
     import sys
     app = QtWidgets.QApplication(sys.argv)
     weight_bt = QtWidgets.QDialog()
     ui = Ui_test()
     ui.setup(weight_bt)
     weight_bt.show()
     sys.exit(app.exec_())