# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bm_manual.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controller.data_io import DataIO

"""
Author: GRP group 14
"""
class Ui_weight_manual(object):
    def setup(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 243)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 150, 200, 80))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setStyleSheet("QPushButton{\n"
                                     "    font-family: Arial;border: 1px solid  #292929;color: #292929; \n"
                                     "    font-weight: bold; padding: 5px 8px;\n"
                                     "}\n"
                                     "QPushButton:hover{                    \n"
                                     "    border: 0px solid7;\n"
                                     "    color:white;background: #292929;\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "    background:#353535;\n"
                                     "}")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(160, 100, 131, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 50, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 100, 72, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.accepted.connect(self.accept_bm)
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def accept_bm(self):
        a_bm = self.textEdit.toPlainText()
        a_bm_final = float(a_bm)

        DataIO.save_bm_temp(a_bm_final)
        DataIO.send_bm_to_db(a_bm_final)

        DataIO.refresh_BM_plot_file()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Weight - Manual Input"))
        self.textEdit.setHtml(_translate("Dialog",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                                         "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.label.setText(_translate("Dialog", "Please enter your weight"))
        self.label_2.setText(_translate("Dialog", "kg"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    weight_manual = QtWidgets.QDialog()
    ui = Ui_weight_manual()
    ui.setup(weight_manual)
    weight_manual.show()
    sys.exit(app.exec_())
