# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bm_measure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controller.scale_connection.scale_connection import Xiaomi_scale
"""
Author: GRP group 14
"""
class Ui_Dialog(object):
    def setup(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setWindowTitle("Weight Measurement Bluetooth")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(60, 220, 200, 50))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setStyleSheet("QPushButton{\n"
                                             "    font-family: Arial;border: 1px solid  #292929;color: #292929; \n"
                                             "    font-size: 14px; font-weight: bold; padding:5px;\n"
                                             "}\n"
                                             "QPushButton:hover{                    \n"
                                             "    border: 0px solid7;\n"
                                             "    color:white;background: #292929;\n"
                                             "}\n"
                                             "QPushButton:pressed{\n"
                                             "    background:#353535;\n"
                                             "}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 50, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.value_display = QtWidgets.QLabel(Dialog)
        self.value_display.setGeometry(QtCore.QRect(130, 100, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.value_display.setFont(font)
        self.value_display.setText("")
        self.value_display.setObjectName("value_display")
        self.MeasureButton = QtWidgets.QPushButton(Dialog)
        self.MeasureButton.setGeometry(QtCore.QRect(110, 180, 191, 31))
        self.MeasureButton.setObjectName("MeasureButton")
        self.MeasureButton.setStyleSheet("QPushButton{\n"
                                             "    font-family: Arial;border: 1px solid  #292929;color: #292929; \n"
                                             "    font-size: 14px; font-weight: bold;\n"
                                             "}\n"
                                             "QPushButton:hover{                    \n"
                                             "    border: 0px solid7;\n"
                                             "    color:white;background: #292929;\n"
                                             "}\n"
                                             "QPushButton:pressed{\n"
                                             "    background:#353535;\n"
                                             "}")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.MeasureButton.clicked.connect(self.connect)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def connect(self):
        scale=Xiaomi_scale()
        self.value_display.setText(str(scale.weight)+" KG")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Weight Measure Bluetooth"))
        self.label.setText(_translate("Dialog", "Taking weight measurement:"))
        self.MeasureButton.setText(_translate("Dialog", "Start"))
