# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectionTimeout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

"""
Author: GRP group 14
"""
class Ui_timeout(object):
    def setupUi(self, timeout):
        timeout.setObjectName("timeout")
        timeout.resize(336, 206)
        self.pushButton = QtWidgets.QPushButton(timeout)
        self.pushButton.setGeometry(QtCore.QRect(130, 150, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.close_window(timeout))
        self.label = QtWidgets.QLabel(timeout)
        self.label.setGeometry(QtCore.QRect(40, 50, 261, 81))
        self.label.setStyleSheet("font: 18pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(timeout)
        QtCore.QMetaObject.connectSlotsByName(timeout)

    def retranslateUi(self, timeout):
        _translate = QtCore.QCoreApplication.translate
        timeout.setWindowTitle(_translate("timeout", "Timeout"))
        self.pushButton.setText(_translate("timeout", "OK"))
        self.label.setText(_translate("timeout", "Connection timeout"))

    def close_window(self, current_window):
        current_window.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    timeout = QtWidgets.QDialog()
    ui = Ui_timeout()
    ui.setupUi(timeout)
    timeout.show()
    sys.exit(app.exec_())
