# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_status.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
Author: GRP group 14
"""
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        self.Dialog = None

    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 186)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 60, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:18px")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pair_bar = QtWidgets.QProgressBar(Dialog)
        self.pair_bar.setGeometry(QtCore.QRect(60, 100, 421, 23))
        self.pair_bar.setProperty("value", 24)
        self.pair_bar.setObjectName("pair_bar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "sensor status"))
        self.label.setAccessibleName(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Connecting..."))

    def progress_ui(self, info):
        self.label.setText(info)

    def progress_bar(self, progress):
        self.pair_bar.setProperty("value", progress)

    def close_window(self):
        self.Dialog.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
