# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_status_successful_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
"""
Author: GRP group 14
"""

class Ui_StatusAcquire(object):
    def setupUi(self, StatusAcquire):
        StatusAcquire.setObjectName("StatusAcquire")
        StatusAcquire.resize(336, 206)
        self.label = QtWidgets.QLabel(StatusAcquire)
        self.label.setGeometry(QtCore.QRect(40, 40, 261, 81))
        self.label.setStyleSheet("font:12pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(StatusAcquire)
        self.pushButton.setGeometry(QtCore.QRect(130, 140, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.close_window(StatusAcquire))

        self.retranslateUi(StatusAcquire)
        QtCore.QMetaObject.connectSlotsByName(StatusAcquire)

    def retranslateUi(self, StatusAcquire):
        _translate = QtCore.QCoreApplication.translate
        StatusAcquire.setWindowTitle(_translate("StatusAcquire", "Acquire Sensor Status"))
        self.label.setText(_translate("StatusAcquire", "Acquire Status Successful"))
        self.pushButton.setText(_translate("StatusAcquire", "OK"))

    def close_window(self, current_window):
        current_window.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StatusAcquire = QtWidgets.QDialog()
    ui = Ui_StatusAcquire()
    ui.setupUi(StatusAcquire)
    StatusAcquire.show()
    sys.exit(app.exec_())
