# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pair_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

"""
Author: GRP group 14
"""
class Ui_pairing(object):
    def __init__(self):
        self.pairing = None

    def setupUi(self, pairing):
        self.pairing = pairing
        pairing.setObjectName("pairing")
        pairing.resize(520, 186)
        self.pair_bar = QtWidgets.QProgressBar(pairing)
        self.pair_bar.setGeometry(QtCore.QRect(60, 100, 421, 23))
        self.pair_bar.setProperty("value", 24)
        self.pair_bar.setObjectName("pair_bar")
        self.label = QtWidgets.QLabel(pairing)
        self.label.setGeometry(QtCore.QRect(60, 60, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font-size:18px")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(pairing)
        QtCore.QMetaObject.connectSlotsByName(pairing)

    def retranslateUi(self, pairing):
        _translate = QtCore.QCoreApplication.translate
        pairing.setWindowTitle(_translate("pairing", "Pairing"))
        self.label.setAccessibleName(_translate("pairing", "0"))
        self.label.setText(_translate("pairing", "Pairing..."))

    def progress_ui(self, info):
        self.label.setText(info)

    def progress_bar(self, progress):
        self.pair_bar.setProperty("value", progress)

    def close_window(self):
        self.pairing.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pairing = QtWidgets.QDialog()
    ui = Ui_pairing()
    ui.setupUi(pairing)
    pairing.show()
    sys.exit(app.exec_())
