# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pair_successful_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

"""
Author: GRP group 14
"""
class Ui_PairingSuccess(object):
    def setupUi(self, PairingSuccess):
        PairingSuccess.setObjectName("PairingSuccess")
        PairingSuccess.resize(336, 206)
        self.label = QtWidgets.QLabel(PairingSuccess)
        self.label.setGeometry(QtCore.QRect(40, 50, 261, 81))
        self.label.setStyleSheet("font:15pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(PairingSuccess)
        self.pushButton.setGeometry(QtCore.QRect(130, 150, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.close_window(PairingSuccess))

        self.retranslateUi(PairingSuccess)
        QtCore.QMetaObject.connectSlotsByName(PairingSuccess)

    def retranslateUi(self, PairingSuccess):
        _translate = QtCore.QCoreApplication.translate
        PairingSuccess.setWindowTitle(_translate("PairingSuccess", "Pairing Success"))
        self.label.setText(_translate("PairingSuccess", "Pairing Successful"))
        self.pushButton.setText(_translate("PairingSuccess", "OK"))

    def close_window(self, current_window):
        current_window.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PairingSuccess = QtWidgets.QDialog()
    ui = Ui_PairingSuccess()
    ui.setupUi(PairingSuccess)
    PairingSuccess.show()
    sys.exit(app.exec_())
